# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
                ('date', models.DateField()),
                ('day_is_relevant', models.BooleanField(default=True)),
                ('month_is_relevant', models.BooleanField(default=True)),
                ('end_date', models.DateField(null=True)),
                ('end_day_is_relevant', models.NullBooleanField()),
                ('end_month_is_relevant', models.NullBooleanField()),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('summary', models.CharField(max_length=256)),
                ('body', models.CharField(max_length=65536)),
                ('references', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Era',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kyc.Category')),
                ('start_year', models.DateTimeField(blank=True, null=True)),
                ('end_year', models.DateTimeField(blank=True, null=True)),
            ],
            bases=('kyc.category',),
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kyc.Category')),
                ('location', models.FilePathField()),
            ],
            bases=('kyc.category',),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kyc.Category')),
            ],
            bases=('kyc.category',),
        ),
        migrations.AddField(
            model_name='story',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='kyc.Category'),
        ),
    ]
